spring:
  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

firebase:
  config-path: ${FIREBASE_CONFIG_PATH:}

---
spring:
  config:
    activate:
      on-profile: dev
    import: classpath:application-dev.properties

---
spring:
  config:
    activate:
      on-profile: prod
    import: classpath:application-prod.properties
