spring:
  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: dev
    import: classpath:application-dev.properties

---
spring:
  config:
    activate:
      on-profile: prod
    import: classpath:application-prod.properties